import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('kmgccc', {
  minimize: () => ipcRenderer.send('window:minimize'),
  toggleMaximize: () => ipcRenderer.send('window:toggle-maximize'),
  close: () => ipcRenderer.send('window:close'),
  getHomeSnapshot: () => ipcRenderer.invoke('library:get-home-snapshot'),
  importAudioFile: () => ipcRenderer.invoke('library:import-audio-file'),
  importAudioFiles: () => ipcRenderer.invoke('library:import-audio-files'),
  importAudioFilesFromPaths: (filePaths: string[]) => ipcRenderer.invoke('library:import-audio-files-from-paths', filePaths),
  syncTrackInfo: (track: unknown) => ipcRenderer.invoke('library:sync-track-info', track),
  lookupAlbumMetadata: (values: Record<string, unknown>) => ipcRenderer.invoke('library:lookup-album-metadata', values),
  lookupArtistMetadata: (values: Record<string, unknown>) => ipcRenderer.invoke('library:lookup-artist-metadata', values),
  lookupLyrics: (values: Record<string, unknown>) => ipcRenderer.invoke('library:lookup-lyrics', values),
  lookupCover: (values: Record<string, unknown>) => ipcRenderer.invoke('library:lookup-cover', values),
  clearLibrary: () => ipcRenderer.invoke('library:clear'),
  updateTrack: (track: unknown) => ipcRenderer.invoke('library:update-track', track),
  deleteTrack: (trackId: string) => ipcRenderer.invoke('library:delete-track', trackId),
  updateAlbum: (albumId: string, values: Record<string, unknown>) => ipcRenderer.invoke('library:update-album', albumId, values),
  deleteAlbum: (albumId: string) => ipcRenderer.invoke('library:delete-album', albumId),
  updateArtist: (artistId: string, values: Record<string, unknown>) => ipcRenderer.invoke('library:update-artist', artistId, values),
  deleteArtist: (artistId: string) => ipcRenderer.invoke('library:delete-artist', artistId),
  createPlaylist: (name: string) => ipcRenderer.invoke('library:create-playlist', name),
  updatePlaylist: (playlistId: string, name: string) => ipcRenderer.invoke('library:update-playlist', playlistId, name),
  deletePlaylist: (playlistId: string) => ipcRenderer.invoke('library:delete-playlist', playlistId),
  addTrackToPlaylist: (playlistId: string, trackId: string) => ipcRenderer.invoke('library:add-track-to-playlist', playlistId, trackId),
  removeTrackFromPlaylist: (playlistId: string, trackId: string) => ipcRenderer.invoke('library:remove-track-from-playlist', playlistId, trackId),
  getLibraryLocation: () => ipcRenderer.invoke('settings:get-library-location'),
  chooseLibraryLocation: () => ipcRenderer.invoke('settings:choose-library-location'),
  showLibraryLocation: () => ipcRenderer.invoke('settings:show-library-location'),
  resetLibraryLocation: () => ipcRenderer.invoke('settings:reset-library-location'),
  clearIndexCache: () => ipcRenderer.invoke('settings:clear-index-cache'),
  clearExternalPlaybackCache: () => ipcRenderer.invoke('settings:clear-external-playback-cache'),
  completeLibraryMetadata: () => ipcRenderer.invoke('settings:complete-library-metadata'),
  getWallpaperTint: () => ipcRenderer.invoke('system:get-wallpaper-tint')
})
